# Base image
FROM python:3.9-slim

# Set working directory inside the container
WORKDIR /app

# Copy dependencies and install
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy training script
COPY train.py .

# Run training script
CMD ["python", "train.py"]