version: "3.8"

services:
  train:
    build:
      context: .
      dockerfile: Dockerfile.train
    volumes:
      - model_storage:/app/models
    command: ["python", "train.py"]

  infer:
    build:
      context: .
      dockerfile: Dockerfile.infer
    depends_on:
      - train
    ports:
      - "8080:8080"
    volumes:
      - model_storage:/app/models

volumes:
  model_storage:
